#pragma once
#include <stddef.h>
#include <stdint.h>

namespace ker::abi::vfs {
enum class ops : uint64_t {
	OPEN,
	READ,
	WRITE,
	CLOSE,
	LSEEK,
	ISATTY,
	READ_DIR_ENTRIES,
	MOUNT,
	MKDIR,
	READLINK,
	SYMLINK,
	SENDFILE,
	STAT,
	FSTAT,
	UMOUNT,
	DUP,
	DUP2,
	GETCWD,
	CHDIR,
	ACCESS,
	UNLINK,
	RMDIR,
	RENAME,
	CHMOD,
	TRUNCATE,
	PIPE,
	PREAD,
	PWRITE,
	FCNTL,
	FCHMOD,
	CHOWN,
	FCHOWN,
	FACCESSAT,
	UNLINKAT,
	RENAMEAT,
	EPOLL_CREATE,
	EPOLL_CTL,
	EPOLL_PWAIT,
	IOCTL,
	FSYNC,
	LINK,
	WKI_RULE_ADD,
	WKI_RULE_GET,
	WKI_RULE_CLEAR,
	PIVOT_ROOT,
	WKI_RULE_GET_DEFAULT,
	STATVFS,
	FSTATVFS,
	LSTAT,
	SYNC,
	REALPATH,
	OPENAT,
	STATAT,
	UTIMENSAT,
	MKDIRAT,
	READLINKAT,
	LINKAT,
	SYMLINKAT,
	FCHMODAT,
	FCHDIR,
	FCHOWNAT,
	FSTAT_CLOSE,
	METADATA_BATCH,
	SETXATTR,
	LSETXATTR,
	FSETXATTR,
	GETXATTR,
	LGETXATTR,
	FGETXATTR,
	LISTXATTR,
	LLISTXATTR,
	FLISTXATTR,
	REMOVEXATTR,
	LREMOVEXATTR,
	FREMOVEXATTR,
	open = OPEN,
	read = READ,
	write = WRITE,
	close = CLOSE,
	lseek = LSEEK,
	isatty = ISATTY,
	read_dir_entries = READ_DIR_ENTRIES,
	mount = MOUNT,
	mkdir = MKDIR,
	readlink = READLINK,
	symlink = SYMLINK,
	sendfile = SENDFILE,
	stat = STAT,
	fstat = FSTAT,
	umount = UMOUNT,
	dup = DUP,
	dup2 = DUP2,
	getcwd = GETCWD,
	chdir = CHDIR,
	access = ACCESS,
	unlink = UNLINK,
	rmdir = RMDIR,
	rename = RENAME,
	chmod = CHMOD,
	truncate = TRUNCATE,
	pipe = PIPE,
	pread = PREAD,
	pwrite = PWRITE,
	fcntl = FCNTL,
	fchmod = FCHMOD,
	chown = CHOWN,
	fchown = FCHOWN,
	faccessat = FACCESSAT,
	unlinkat = UNLINKAT,
	renameat = RENAMEAT,
	epoll_create = EPOLL_CREATE,
	epoll_ctl = EPOLL_CTL,
	epoll_pwait = EPOLL_PWAIT,
	ioctl = IOCTL,
	fsync = FSYNC,
	link = LINK,
	wki_rule_add = WKI_RULE_ADD,
	wki_rule_get = WKI_RULE_GET,
	wki_rule_clear = WKI_RULE_CLEAR,
	pivot_root = PIVOT_ROOT,
	wki_rule_get_default = WKI_RULE_GET_DEFAULT,
	statvfs = STATVFS,
	fstatvfs = FSTATVFS,
	lstat = LSTAT,
	sync = SYNC,
	realpath = REALPATH,
	openat = OPENAT,
	statat = STATAT,
	utimensat = UTIMENSAT,
	mkdirat = MKDIRAT,
	readlinkat = READLINKAT,
	linkat = LINKAT,
	symlinkat = SYMLINKAT,
	fchmodat = FCHMODAT,
	fchdir = FCHDIR,
	fchownat = FCHOWNAT,
	fstat_close = FSTAT_CLOSE,
	metadata_batch = METADATA_BATCH,
	setxattr = SETXATTR,
	lsetxattr = LSETXATTR,
	fsetxattr = FSETXATTR,
	getxattr = GETXATTR,
	lgetxattr = LGETXATTR,
	fgetxattr = FGETXATTR,
	listxattr = LISTXATTR,
	llistxattr = LLISTXATTR,
	flistxattr = FLISTXATTR,
	removexattr = REMOVEXATTR,
	lremovexattr = LREMOVEXATTR,
	fremovexattr = FREMOVEXATTR,
};

constexpr size_t XATTR_NAME_MAX = 255;
constexpr size_t XATTR_SIZE_MAX = 65536;
constexpr size_t XATTR_LIST_MAX = 65536;

constexpr uint16_t METADATA_BATCH_VERSION = 1;
constexpr uint8_t METADATA_BATCH_MAX_ITEMS = 64;
constexpr size_t METADATA_BATCH_MAX_PATH_CHARS = 511;

enum class metadata_batch_operation : uint8_t {
	INVALID = 0,
	CREATE_CLOSE = 1,
	STAT_FOLLOW = 2,
	UNLINK = 3,
	RENAME = 4,
	invalid = INVALID,
	create_close = CREATE_CLOSE,
	stat_follow = STAT_FOLLOW,
	unlink = UNLINK,
	rename = RENAME,
};

struct metadata_batch_header {
	uint16_t version;
	metadata_batch_operation operation;
	uint8_t count;
	uint32_t mode;
};

static_assert(static_cast<uint64_t>(ops::METADATA_BATCH) == 62);
static_assert(static_cast<uint64_t>(ops::SETXATTR) == 63);
static_assert(static_cast<uint64_t>(ops::FREMOVEXATTR) == 74);
static_assert(sizeof(metadata_batch_header) == 8);
} // namespace ker::abi::vfs
