#ifndef MLIBC_ABIS_WOS_XATTR_H
#define MLIBC_ABIS_WOS_XATTR_H

enum {
	XATTR_CREATE = 1,
#define XATTR_CREATE XATTR_CREATE
	XATTR_REPLACE = 2
#define XATTR_REPLACE XATTR_REPLACE
};

#endif /* MLIBC_ABIS_WOS_XATTR_H */
